name: "build_image"

on:
  push:
    paths:
      - "**"
      - "!README.md"

jobs:
  build:
    uses: tiredofit/github_actions/.github/workflows/default_amd64_armv7_arm64.yml@main
    #uses: tiredofit/github_actions/.github/workflows/default_amd64.yml@main
    #uses: tiredofit/github_actions/.github/workflows/default_amd64_armv7_arm64.yml@main
    #uses: tiredofit/github_actions/.github/workflows/default_amd64_arm64.yml@main
    secrets: inherit
